1 - Create an array with 15 random floating-point numbers between 0 and 1. Compute the mean, median, standard deviation, and variance.


In [ ]:
import numpy as np

# Create an array with 15 random floating-point numbers between 0 and 1
array = np.random.rand(15)
print("Array:")
print(array)

# Compute statistical operations
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("\nMean:")
print(mean)
print("Median:")
print(median)
print("Standard Deviation:")
print(std_dev)
print("Variance:")
print(variance)


Array:
[0.42897138 0.60929756 0.15780542 0.30456837 0.94724876 0.78979036
 0.67399345 0.00804572 0.1706217  0.62953779 0.59724037 0.62275051
 0.13380231 0.998935   0.08587377]

Mean:
0.4772321662814752
Median:
0.5972403743672458
Standard Deviation:
0.30823579693862124
Variance:
0.09500930651438695


2 -Create two 3x2 and 2x3 matrices with random integers. Perform matrix multiplication on these matrices.

In [ ]:
import numpy as np

# Create a 3x2 and a 2x3 matrix with random integers
matrix1 = np.random.randint(1, 10, size=(3, 2))
matrix2 = np.random.randint(1, 10, size=(2, 3))

print("Matrix 1 (3x2):")
print(matrix1)
print("\nMatrix 2 (2x3):")
print(matrix2)

# Perform matrix multiplication
product = np.dot(matrix1, matrix2)

print("\nMatrix Multiplication Result:")
print(product)


Matrix 1 (3x2):
[[7 2]
 [9 3]
 [5 2]]

Matrix 2 (2x3):
[[8 3 6]
 [6 4 1]]

Matrix Multiplication Result:
[[68 29 44]
 [90 39 57]
 [52 23 32]]


3 -Create two 3x3 matrices with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these matrices.


In [ ]:
import numpy as np

# Create two 3x3 matrices with random integers between 1 and 10
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Perform element-wise operations
addition = np.add(matrix1, matrix2)
subtraction = np.subtract(matrix1, matrix2)
multiplication = np.multiply(matrix1, matrix2)
division = np.divide(matrix1, matrix2)

print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Matrix 1:
[[6 7 4]
 [2 3 9]
 [7 7 9]]

Matrix 2:
[[7 2 5]
 [4 8 1]
 [3 4 7]]

Element-wise Addition:
[[13  9  9]
 [ 6 11 10]
 [10 11 16]]

Element-wise Subtraction:
[[-1  5 -1]
 [-2 -5  8]
 [ 4  3  2]]

Element-wise Multiplication:
[[42 14 20]
 [ 8 24  9]
 [21 28 63]]

Element-wise Division:
[[0.85714286 3.5        0.8       ]
 [0.5        0.375      9.        ]
 [2.33333333 1.75       1.28571429]]


4 - Create a 2D array with random integers between 0 and 50, with dimensions 4x5. Find the sum of each row and each column.

In [ ]:
import numpy as np

# Create a 2D array with random integers between 0 and 50
array = np.random.randint(0, 50, size=(4, 5))
print("Original Array:")
print(array)

# Find the sum of each row
row_sums = np.sum(array, axis=1)
print("\nSum of each row:")
print(row_sums)

# Find the sum of each column
col_sums = np.sum(array, axis=0)
print("\nSum of each column:")
print(col_sums)


Original Array:
[[42 35 22 29 20]
 [31 31 40 21 13]
 [31 18 32  5 36]
 [36  3 33 32 48]]

Sum of each row:
[148 136 122 152]

Sum of each column:
[140  87 127  87 117]
